version: '3'

services:
  web:
    build:
      context: ./front-end
      dockerfile: .docker/Dockerfile
    container_name: angular
    ports:
      - "4200:80"
    depends_on:
      - api

  api:
    build:
      context: ./back-end
      dockerfile: .docker/Dockerfile
    container_name: nestjs
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=postgres

  db:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "2345:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: